apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
  name: fastapi
spec:
  selector:
    app: fastapi
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
  type: LoadBalancer